# Generated by Django 3.2 on 2022-08-19 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('sku', models.CharField(max_length=50, validators=[utils.validators.SKUValidator()], verbose_name='stock keeping unit')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('avatar', models.ImageField(blank=True, upload_to='packages/', verbose_name='avatar')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('duration', models.IntegerField(default=0, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'db_table': 'package',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_time', models.DateField(blank=True, null=True, verbose_name='expire time')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is enabled')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.package', verbose_name='package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscription',
                'abstract': False,
            },
        ),
    ]
