# Generated by Django 3.2 on 2022-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'invalid': 'Enter a valid phone number. This value may contain only digits.'}, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
