# Generated by Django 3.2 on 2022-08-19 09:14

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, error_messages={'invalid': 'Enter a valid phone number. This value may contain only digits.'}, unique=True, validators=[utils.validators.PhoneNumberValidator()], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='A required field. At least 32 characters long or fewer letter, Letters or digits .', max_length=32, unique=True, validators=[utils.validators.UsernameValidators()], verbose_name='username'),
        ),
    ]
